#ifndef RESOURCE_H
#define RESOURCE_H

#define IDI_APP_ICON 101
#define IDI_TRAY_ICON 102
#define IDI_TRAY_LIGHT_ICON 102
#define IDI_TRAY_DARK_ICON 103
#define IDI_TRAY_COLOR_ICON 104

#endif // RESOURCE_H
